spring:

  # Database #
  datasource:
    url: //localhost:3306/test
    username: root
    password: root
    database:
      name: test
      schemas:
        table-cadastral-user:
          name: tb001_usuario_cadastral
        table-consolidated-user:
          name: tb002_usuario_consolidado

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

