spring:

  # Database #
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/prosperah_db_rel_corev1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    database:
      name: prosperah_db_rel_corev1
      schemas:
        table-cadastral-user:
          name: tb001_usuario_cadastral
        table-consolidated-user:
          name: tb002_usuario_consolidado

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

