spring:

  # Database #
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/prosperah_db_rel_corev1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    database:
      name: prosperah_db_rel_corev1
      schemas:
        table-cadastral-user: tb001_usuario_cadastral
        table-consolidated-user: tb002_usuario_consolidado

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  # Email #
mail:
  protocol:
    transport-strategy: SMTP_TLS
  smtp:
    host: smtp.default.com
    port: 25
    username: username
    password: password
  defaults:
    content:
      transfer:
        encoding: BINARY
  subject: Titulo de teste para envio de email

