on:
  push:
    branches:
      - "feature*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
    uses: diillson/auto-pull-request@v1.0.1
      with:
        source_branch: "develop/*"                                 # If blank, default: triggered branch
        destination_branch: "develop"                       # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into develop" # Title of pull request
        pr_body: |                                        # Full markdown support, requires pr_title to be set
          :crown: *An automated PR*