name: Build and PR Pipeline

on:
  push:
    branches:
      - feature/*  # Altere conforme necessário para a branch que deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'openjdk11'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          head: feature/*  # Altere conforme necessário para a branch que deseja usar como origem
          title: "Automated Pull Request - Build and Tests Passed"
          body: |
            This pull request was automatically created by a GitHub Action.
            All tests have passed and the build was successful.
          branch: automated-pull-request-branch