name: Build and PR Pipeline

on:
  push:
    branches:
      - feature/*  # Altere conforme necessário para a branch que deseja monitorar

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  get_branch_name:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current branch name
        id: branch_name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"


  create_pr:
    needs: get_branch_name
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.get_branch_name.outputs.branch_name }}
          title: "Merge to develop"
          body: "This PR merges changes from ${{ steps.get_branch_name.outputs.branch }} into develop"
          base: develop